version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRESS_DB: library_db
    ports:
      - "5432:5432"
  back:
    build:
      context: ./library_back
      dockerfile: Dockerfile
    command: python library_back/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db