name: Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Install
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Autopep8 install
        run: |
          python -m pip install --upgrade pip
          pip install -Iv autopep8==1.7.0
      - name: Linter Execute (autopep8)
        run: python -m autopep8 actions --exit-code
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: Build docker
      run: docker-compose build --no-cache
    - name: Make migrations
      run: docker-compose run back python manage.py makemigrations
    - name: Migrate
      run: docker-compose run back python manage.py migrate
  tests:
    runs-on: ubuntu-latest
    name: "Tests"
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: Back test
      run: docker-compose run back python -m pytest accounts books
    - name: Front test
      run: docker-compose run front npm run test
  
