name: Library CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: Build docker
      run: docker-compose build --no-cache
    - name: Make migrations
      run: docker-compose run back python manage.py makemigrations
    - name: Migrate
      run: docker-compose run back python manage.py migrate
  tests:
    runs-on: ubuntu-latest
    name: "Tests"
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3
    - name: Back test
      run: docker-compose run back python -m pytest accounts books
    - name: Front test
      run: docker-compose run front npm run test
  
